[language-server.jdtls]
command = "jdtls"
args = ["-configuration", "/home/t-aaronobelley/.cache/jdtls/config_linux", "-data", "/home/t-aaronobelley/.cache/jdtls/workspace"]

[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle"]
indent = { tab-width = 4, unit = "    " }
language-servers = ["jdtls"]

[language-server.lemminx]
command = "lemminx"


[[language]]
name = "xml"
auto-format = false
file-types = [ "xml", "svg", "xsd", "xslt", "xsl" ]
formatter = { command = "xmllint", args = ["--format", "-"] }
language-servers = [ "xml" ]

[[language]]
name = "nix"
formatter = { command = "nixfmt" }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"]}
